In [2]:
Output = '/Users/alexis/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/CEMALB_DataAnalysisPM/Projects/P1013. Microbiome Peanut Allergy/P1013.3. Analyses/P1013.6. Boxplots/Output'
cur_date = '032626'

library(readxl)
library(openxlsx)
library(writexl)
library(tidyverse)
#library(factoextra)
library(ggpubr)

# reading in files
saliva_df = data.frame(read_excel("Input/Processed_Saliva_Data_090525.xlsx")) %>%
    mutate(Age = as.numeric(Age), IgE = as.numeric(IgE)) 
stool_df = data.frame(read_excel("Input/Processed_Stool_Data_090525.xlsx")) %>%
    mutate(Age = as.numeric(Age), IgE = as.numeric(IgE))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa

In [3]:
head(saliva_df)

  Original_Sample_ID Subject_No Sample_ID Time_Point Treatment Outcome Age
1 FS01baseline       1          Pre_1     Pre        P         F       3.838356
2 FS0236mo           2          Post_2    Post       A         DS      1.873973
3 FS02baseline       2          Pre_2     Pre        A         DS      1.873973
4 FS0436mo           3          Post_3    Post       P         F       3.715068
5 FS04baseline       3          Pre_3     Pre        P         F       3.715068
6 FS0536mo           4          Post_4    Post       A         DS      3.991781
  IgE   IgE_Binarized k__Bacteria.__.__.__.__.__.__ ⋯
1 41.00 High           7                            ⋯
2 14.20 Low           63                            ⋯
3 14.20 Low            0                            ⋯
4 67.40 High          34                            ⋯
5 67.40 High           4                            ⋯
6  9.59 Low            6                            ⋯
  k__Bacteria.p__Proteobacteria.c__Gammaproteobacteria.o__Pasteurellales.f__Pasteurellaceae.__.__
1  57
2 698
3   0
4   0
5   0
6   0
  k__Bacteria.p__Proteobacteria.c__Gammaproteobacteria.o__Pasteurellales.f__Pasteurellaceae.g__Aggregatibacter.__
1 13
2  0
3  0
4  0
5  0
6 17
  k__Bacteria.p__Proteobacteria.c__Gammaproteobacteria.o__Pasteurellales.f__Pasteurellaceae.g__Aggregatibacter.s__aphrophilus
1  0
2 43
3 46
4  0
5  0
6  0
  k__Bacteria.p__Proteobacteria.c__Gammaproteobacteria.o__Pasteurellales.f__Pasteurellaceae.g__Haemophilus.__
1 213
2  98
3 371
4   0
5   0
6 139
  k__Bacteria.p__Proteobacteria.c__Gammaproteobacteria.o__Pasteurellales.f__Pasteurellaceae.g__Haemophilus.s__parainfluenzae
1  775
2 1657
3 3359
4   92
5   43
6 2521
  k__Bacteria.p__Saccharibacteria_.TM7..c__Saccharibacteria_.TM7._.C.1..o__Saccharibacteria_.TM7._.O.1..f__Saccharibacteria_.TM7._.F.1..g__Saccharibacteria_.TM7._.G.1..__
1   0
2   0
3   0
4   0
5 414
6   0
  k__Bacteria.p__Saccharibacteria_.TM7..c__Saccharibacteria_.TM7._.C.1..o__Saccharibacteria_.TM7._.O.1..f__Saccharibacteria_.TM7._.F.1..g__Saccharibacteria_.TM7._.G.1..s__bacterium_HMT_347
1  14
2   0
3   0
4 200
5  47
6   0
  k__Bacteria.p__Saccharibacteria_.TM7..c__Saccharibacteria_.TM7._.C.1..o__Saccharibacteria_.TM7._.O.1..f__Saccharibacteria_.TM7._.F.1..g__Saccharibacteria_.TM7._.G.1..s__bacterium_HMT_352
1 246
2 423
3   0
4  67
5   0
6 502
  k__Bacteria.p__Saccharibacteria_.TM7..c__Saccharibacteria_.TM7._.C.1..o__Saccharibacteria_.TM7._.O.1..f__Saccharibacteria_.TM7._.F.1..g__Saccharibacteria_.TM7._.G.3..s__bacterium_HMT_351
1  44
2 146
3   0
4  32
5   2
6  39
  k__Bacteria.p__Saccharibacteria_.TM7..c__Saccharibacteria_.TM7._.C.1..o__Saccharibacteria_.TM7._.O.1..f__Saccharibacteria_.TM7._.F.1..g__Saccharibacteria_.TM7._.G.6..s__bacterium_HMT_870
1   64
2  123
3  112
4  201
5 1050
6  101

Using boxplots to compare bacteria of interest.

In [4]:
# first cleaning up the dataframes
combined_saliva_df = saliva_df  %>%
    # ended up reassinging 'DS' to 'F' due to small sample size
    mutate(Outcome = ifelse(Outcome == 'DS', 'F', Outcome)) %>%
    # removing those failed the IgE protein
    filter(IgE_Binarized != 'Fail') %>%
    pivot_longer(cols = 10:127, values_to = 'Value', names_to = 'Name') %>%
    # cleaning up names
    separate(Name, c("Name", "Name1"), sep = '.g__') %>%
    mutate(across(Name1, ~ str_replace(string = .x, ".s__", " ")),
          across(Name1, ~ str_replace(string = .x, "sp._", "")),
          across(Name1, ~ str_replace(string = .x, ".__", "")),
          Name1 = ifelse(Name == 'k__Bacteria.__.__.__.__.__.__' , 'Unassigned', Name1))

# combined_stool_df = stool_df  %>%
#     # ended up reassinging 'DS' to 'F' due to small sample size
#     mutate(Outcome = ifelse(Outcome == 'DS', 'F', Outcome)) %>%
#     filter(IgE_Binarized != 'Fail')

head(combined_saliva_df)

Warning message:
“Expected 2 pieces. Missing pieces filled with `NA` in 325 rows [1, 44, 99, 108,
109, 119, 162, 217, 226, 227, 237, 280, 335, 344, 345, 355, 398, 453, 462, 463,
...].”

  Original_Sample_ID Subject_No Sample_ID Time_Point Treatment Outcome Age
1 FS01baseline       1          Pre_1     Pre        P         F       3.838356
2 FS01baseline       1          Pre_1     Pre        P         F       3.838356
3 FS01baseline       1          Pre_1     Pre        P         F       3.838356
4 FS01baseline       1          Pre_1     Pre        P         F       3.838356
5 FS01baseline       1          Pre_1     Pre        P         F       3.838356
6 FS01baseline       1          Pre_1     Pre        P         F       3.838356
  IgE IgE_Binarized
1 41  High
2 41  High
3 41  High
4 41  High
5 41  High
6 41  High
  Name
1 k__Bacteria.__.__.__.__.__.__
2 k__Bacteria.p__Absconditabacteria_.SR1..c__Absconditabacteria_.SR1._.C.1..o__Absconditabacteria_.SR1._.O.1..f__Absconditabacteria_.SR1._.F.1.
3 k__Bacteria.p__Absconditabacteria_.SR1..c__Absconditabacteria_.SR1._.C.1..o__Absconditabacteria_.SR1._.O.1..f__Absconditabacteria_.SR1._.F.1.
4 k__Bacteria.p__Actinobacteria.c__Actinomycetia.o__Actinomycetales.f__Actinomycetaceae
5 k__Bacteria.p__Actinobacteria.c__Actinomycetia.o__Actinomycetales.f__Actinomycetaceae
6 k__Bacteria.p__Actinobacteria.c__Actinomycetia.o__Actinomycetales.f__Actinomycetaceae
  Name1                                            Value
1 Unassigned                                         7
2 Absconditabacteria_.SR1._.G.1. bacterium_HMT_874  30
3 Absconditabacteria_.SR1._.G.1. bacterium_HMT_875   8
4 Actinomyces                                      136
5 Actinomyces graevenitzii                           8
6 Schaalia lingnae                                   0